=== dtee/scraper/Report/Summer Intern/crawlconfig/Config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 sp1 (http://www.altova.com) by David (EMBRACE) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.ten45.com/domain/crawler" targetNamespace="http://www.ten45.com/domain/crawler" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Merchants">
		<xs:annotation>
			<xs:documentation>Merchant Information</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Merchant" type="Merchant"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Group">
		<xs:annotation>
			<xs:documentation>Extraction information for the group of URLs</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Category" type="Category" minOccurs="0"/>
			<xs:element name="Product" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="Product"/>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Link" type="Link" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="Name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="2"/>
					<xs:maxLength value="20"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="Category">
		<xs:annotation>
			<xs:documentation>NestedCategory Information</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="ExtractionElement">
				<xs:sequence>
					<xs:element name="Category" type="Category" minOccurs="0"/>
				</xs:sequence>
				<xs:attribute name="XSLLink" type="xs:string" use="optional"/>
				<xs:attribute name="Group" type="xs:string"/>
				<xs:attribute name="Href" type="xs:string"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Merchant">
		<xs:sequence>
			<xs:element name="Site" type="Site" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="Name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="Site">
		<xs:sequence>
			<xs:element name="CategoryCrawl">
				<xs:complexType>
					<xs:attribute name="Group" type="xs:string" use="required"/>
					<xs:attribute name="Url" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="ProductCrawl">
				<xs:complexType>
					<xs:attribute name="Group" type="xs:string"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="Group" type="Group" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="Url" type="xs:string" use="required"/>
		<xs:attribute name="Name" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:minLength value="3"/>
					<xs:maxLength value="20"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="DownloadDelay" type="xs:integer" use="required"/>
		<xs:attribute name="ProductIDAttribute" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="primaryIdentifier.feedId"/>
					<xs:enumeration value="primaryIdentifier.sku"/>
					<xs:enumeration value="primaryIdentifier.upc"/>
					<xs:enumeration value="impressionUrl"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="Product">
		<xs:complexContent>
			<xs:extension base="ExtractionElement"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="Link">
		<xs:complexContent>
			<xs:extension base="ExtractionElement">
				<xs:attribute name="Href" type="xs:string" use="required"/>
				<xs:attribute name="Group" type="xs:string" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="AttributeType">
		<xs:attribute name="XPath" type="xs:string" use="required"/>
		<xs:attribute name="AttributeName" type="xs:string" use="required"/>
		<xs:attribute name="DataType" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="string"/>
					<xs:enumeration value="int"/>
					<xs:enumeration value="float"/>
					<xs:enumeration value="date"/>
					<xs:enumeration value="Money"/>
					<xs:enumeration value="URL"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="CategoryHyperName">
		<xs:restriction base="xs:string">
			<xs:enumeration value="DISPLAYNAME"/>
			<xs:enumeration value="URL"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ProductHyperName">
		<xs:restriction base="xs:string">
			<xs:enumeration value="pricing.price"/>
			<xs:enumeration value="pricing.fromPrice"/>
			<xs:enumeration value="pricing.discount"/>
			<xs:enumeration value="primaryIdentifier.sku"/>
			<xs:enumeration value="title"/>
			<xs:enumeration value="keywords"/>
			<xs:enumeration value="brand"/>
			<xs:enumeration value="gender"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="ExtractionElement" abstract="true">
		<xs:sequence>
			<xs:element name="Attribute" type="AttributeType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="XPath" type="xs:string" use="required"/>
		<xs:attribute name="ClassName" type="xs:string" use="optional"/>
	</xs:complexType>
</xs:schema>

=== dtee/scraper/Report/Summer Intern/crawlconfig/backcountry.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2006 rel. 3 sp1 (http://www.altova.com)-->
<Merchants xmlns="http://www.ten45.com/domain/crawler" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ten45.com/domain/crawler
C:\ten45\trunk\platform\xml\src\xsd\Config.xsd">
	<Merchant Name="backcountry.com">
		<Site Url="http://www.backcountry.com" Name="BackCountry" DownloadDelay="0" ProductIDAttribute="impressionUrl">
			<!--CategoryCrawl Group="Product1" Url="/store/GER0043/c1/s6/Gerber-Presto-3.5-Serrated-Edge-Knife.html?id=kLyGKH2y"/-->			
			<!-- CategoryCrawl Group="List1" Url="/store/group/164/c100000009/s21/Mens-Sandals.html"/-->
			<!-- CategoryCrawl Group="Category1" Url="/store/site_map/c12/Womens-Clothing.html"/-->
            
            <CategoryCrawl Group="SiteMap" Url="/store/site_map.html"/>
			<ProductCrawl Group="List1"/>
            
			<Group Name="SiteMap">
				<Category ClassName="ProductCategory" Href="./@href" XPath=".//TD/@width[contains(.,'20%')]/parent::*/A/@href[contains(.,'site_map')]/parent::*" Group="Cata1">
					<Attribute XPath="./." AttributeName="displayName" DataType="string"/>
					<Attribute XPath="./@href" AttributeName="url" DataType="URL"/>
				</Category>
			</Group>
            
			<Group Name="Cata1">
				<Category ClassName="ProductCategory" Href="./@href" XPath="//FONT/@color[contains(.,'1E6EA7')]/parent::*//A" Group="Cata2">
					<Attribute XPath="./." AttributeName="displayName" DataType="string"/>
					<Attribute XPath="./@href" AttributeName="url" DataType="URL"/>
				</Category>
			</Group>
            
			<Group Name="Cata2">
				<Category ClassName="ProductCategory" XPath="//TD/@class[contains(.,'brevmed')]/parent::*">
					<Attribute XPath=".//FONT" AttributeName="displayName" DataType="string"/>
					<Attribute XPath=".//A/@href" AttributeName="url" DataType="URL"/>
				</Category>
			</Group>
            
			<Group Name="List1">
				<Link Group="Product1"  ClassName="UrlInfo"  XPath="//TD/@bgcolor[contains(.,'EEEEEE')]/parent::*/parent::*//IMG/@alt/parent::*/parent::*" Href="./@href">
				</Link>
			</Group>
            
			<Group Name="Product1">
				<Product ClassName="OnlineProduct" XPath=".">
					<Attribute XPath=".//META[@name='PRODUCT_TITLE']/@content" AttributeName="title" DataType="string"/>
                    <Attribute XPath=".//A/@href" AttributeName="rawImageUrl" DataType="URL"/>
					<Attribute XPath=".//META[@name='PRODUCT_PRICE']/@content" AttributeName="pricing.lowerSalePrice" DataType="float"/>
					<Attribute XPath=".//META[@name='PRODUCT_ORIGPRICE']/@content" AttributeName="pricing.upperSalePrice" DataType="float"/>
				</Product>
			</Group>
            
            <Group Name="Category1">
                <Category ClassName="ProductCategory" XPath=".//TD[@id='content']">
                    <Attribute XPath=".//BR/following-sibling::B" DataType="string" AttributeName="displayName"/>
                    <Category ClassName="ProductCategory" XPath=".//FONT/B">
                        <Attribute XPath="./A/@href" DataType="string" AttributeName="url"/>
                        <Attribute XPath="./A" DataType="string" AttributeName="displayName"/>
                        <Category ClassName="ProductCategory" XPath="./parent::*/parent::*/parent::*/parent::*//TD[@width='33%']">
                            <Attribute XPath="./A/@href" DataType="string" AttributeName="url"/>
                            <Attribute XPath="./A" DataType="string" AttributeName="displayName"/>
                        </Category>
                    </Category>
                </Category>
            </Group>
		</Site>
	</Merchant>
</Merchants>

=== dtee/scraper/Report/Summer Intern/crawlconfig/chadwicks.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2006 rel. 3 sp1 (http://www.altova.com)-->
<Merchants xmlns="http://www.ten45.com/domain/crawler" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ten45.com/domain/crawler
C:\ten45\trunk\platform\xml\src\xsd\Config.xsd">
    <Merchant Name="ChadWicks.com">
        <Site Url="http://www.chadwicks.com" DownloadDelay="0" Name="ChadWicks.com" ProductIDAttribute="impressionUrl">
            <CategoryCrawl Group="Main" Url="/"/>
            <ProductCrawl Group="String"/>
            <Group Name="Main">
                <Category Group="Cata1" Href=".//A/@href" ClassName="ProductCategory" XSLLink="" XPath="//A/@id[contains(.,'Head')]/parent::*//@href[contains(.,'depart')]/ancestor::TD">
                    <Attribute XPath=".//IMG/@alt" DataType="string" AttributeName="displayName"/>
                    <Attribute XPath=".//A/@href" DataType="URL" AttributeName="url"/>
                </Category>
            </Group>
            <Group Name="Cata1">
                <Category ClassName="ProductCategory" XPath="//A/@id[contains(.,'eftNavigat')]/parent::*" Group="CataProdct1" Href="./@href">
                    <Attribute XPath="." DataType="string" AttributeName="displayName"/>
                    <Attribute XPath="./@href" DataType="URL" AttributeName="url"/>
                </Category>
            </Group>
            <Group Name="CataProdct1">
                <Category ClassName="ProductCategory" Href="./@href" XPath="//A/@id[contains(.,'DepartmentChildren')]/..">
                    <Attribute XPath="." DataType="string" AttributeName="displayName"/>
                    <Attribute XPath="./@href" DataType="URL" AttributeName="url"/>
                </Category>
            </Group>
            <Group Name="ProductList">          
                <Link Group="Product" Href="./@href" ClassName="UrlLink" XPath="//TD//IMG[@width=125][@height=180]/parent::*"/>
            </Group>
            <Group Name="Product">
                <Product ClassName="OnlineProduct" XPath=".">
                    <Attribute XPath=".//SPAN[@id='Summary1_lblName']/B|.//SPAN[@id='Summary1_lblName']" DataType="string" AttributeName="title"/>
                    <Attribute XPath=".//SPAN[@id='Summary1_lblPrice']" DataType="Money" AttributeName="pricing.lowerSalePrice"/>
                    <Attribute XPath=".//SPAN[@class='salepricestyle']/FONT" DataType="Money" AttributeName="pricing.upperSalePrice"/>
                    <Attribute XPath=".//IMG/@id[contains(.,'MainImage')]/../@src" DataType="URL" AttributeName="imageUrl"/>
                    <Attribute XPath=".//SPAN[@id='Summary1_lblDescription']" DataType="string" AttributeName="longDescription"/>
                </Product>
            </Group>
        </Site>
    </Merchant>
</Merchants>

=== dtee/scraper/Report/Summer Intern/crawlconfig/bareEsscentuals.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2006 rel. 3 sp1 (http://www.altova.com)-->
<Merchants xmlns="http://www.ten45.com/domain/crawler" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.ten45.com/domain/crawler
C:\ten45\trunk\platform\xml\src\xsd\Config.xsd">
	<Merchant Name="Bare Escentuals">
		<Site DownloadDelay="0" Name="mdformulations" Url="http://www.mdformulations.com" ProductIDAttribute="impressionUrl">
			<CategoryCrawl Group="Main" Url="/jump.jsp?itemID=0&amp;itemType=HOME_PAGE"/>
			<ProductCrawl Group="Product"/>
			<Group Name="Main">
				<Category Group="Cata1" Href="./@href" XPath="//TD[@colspan='3']//TABLE//TD/A">
					<Attribute XPath="./@href" DataType="URL" AttributeName="url"/>
					<Attribute XPath="./IMG/@alt" DataType="string" AttributeName="displayName"/>
				</Category>
			</Group>
			<Group Name="Cata1">
				<Category Group="Link" Href="./@href" XPath="//TABLE[@width='252']//TR[@valign='top']//A">
					<Attribute XPath="./@href" DataType="URL" AttributeName="url"/>
					<Attribute XPath="./IMG/@alt" DataType="string" AttributeName="displayName"/>
				</Category>
			</Group>
			<Group Name="Link">
				<Link Group="Product" Href="./../@href" XPath="//TD[@width='146']//B"/>
			</Group>
			<Group Name="Product">
				<Product ClassName="OnlineProduct" XPath=".">
					<Attribute XPath=".//DIV[@class='defaultsubheader']" AttributeName="title" DataType="string"/>
					<Attribute XPath=".//DIV[@align='center']/IMG/@src" AttributeName="imageUrl" DataType="URL"/>
					<Attribute XPath=".//DIV[@class='default']" AttributeName="description" DataType="string"/>
					<!--Attribute XPath=".//SPAN[@class='tableitem']" AttributeName="mft" DataType="int"/-->
					<Attribute XPath=".//DIV[@class='messageWasPrice']" AttributeName="pricing.upperSalePrice" DataType="Money"/>
				</Product>
			</Group>
		</Site>
	</Merchant>
</Merchants>
